export const themes = {
  theme1: {
    name: "Sunrise Gold",
    primary: "#FFBC42",
    secondary: "#FFEDCC",
    tertiary: "#42D9FF",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0A0A0A",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  theme2: {
    name: "Orange Boost",
    primary: "#FF8D03",
    secondary: "#FF981B",
    tertiary: "#FFAC47",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0A0A0A",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  theme3: {
    name: "Golden Pulse",
    primary: "#FCAA05",
    secondary: "#FCBA35",
    tertiary: "#FCCB68",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0A0A0A",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  theme4: {
    name: "Green Vitality",
    primary: "#00A63D",
    secondary: "#95BF75",
    tertiary: "#B0CF97",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0A0A0A",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  theme5: {
    name: "Lime Surge",
    primary: "#00A63D",
    secondary: "#88E34F",
    tertiary: "#A7EB7C",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0A0A0A",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  theme6: {
    name: "Fresh Meadow",
    primary: "#00A63D",
    secondary: "#8ACC64",
    tertiary: "#A6D98B",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0A0A0A",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  theme7: {
    name: "Active Green",
    primary: "#00A63D",
    secondary: "#E8F4E5",
    tertiary: "#2F80ED",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F6FAF5",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    backgroundDark: "#0D0F0E",
    surfaceDark: "#1A1D1A",
    textDark: "#F5F5F5",
    textMutedDark: "#A5A5A5",
  },
  themeRed: {
    name: "Red Power",
    primary: "#E63946",
    secondary: "#F9D5D7",
    tertiary: "#FF6B6B",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F7F1F1",
    textLight: "#111111",
    textMutedLight: "#656565",
    backgroundDark: "#0D0D0F",
    surfaceDark: "#1A1718",
    textDark: "#F5F5F5",
    textMutedDark: "#A6A6A6",
  },
  themeBlue: {
    name: "Blue Focus",
    primary: "#2F80ED",
    secondary: "#D6E6FC",
    tertiary: "#56CCF2",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F3F7FD",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    backgroundDark: "#0C0E12",
    surfaceDark: "#161920",
    textDark: "#F5F5F5",
    textMutedDark: "#A5A5A5",
  },
  themeOrange: {
    name: "Orange Boost",
    primary: "#F57C00",
    secondary: "#FFE3C2",
    tertiary: "#FF9800",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#FFF7EE",
    textLight: "#111111",
    textMutedLight: "#6A6A6A",
    backgroundDark: "#0F0E0B",
    surfaceDark: "#1C1A16",
    textDark: "#F5F5F5",
    textMutedDark: "#A9A9A9",
  },
  themeYellow: {
    name: "Yellow Drive",
    primary: "#F2C94C",
    secondary: "#FFF1C6",
    tertiary: "#F8D96D",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#FFF9E8",
    textLight: "#111111",
    textMutedLight: "#636363",
    borderLight: "#D4D4D4",
    backgroundDark: "#0E0D06",
    surfaceDark: "#1B190E",
    textDark: "#F5F5F5",
    textMutedDark: "#A5A27A",
    borderDark: "#2A2A2A",
  },
  themeA: {
    name: "Blue Orange Gray",
    primary: "#2F80ED",
    secondary: "#FF8A34",
    tertiary: "#FFB366",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F5F7FA",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    borderLight: "#E1E4E8",
    backgroundDark: "#0C0E12",
    surfaceDark: "#15181D",
    textDark: "#F5F5F5",
    textMutedDark: "#9CA3AF",
    borderDark: "#2A2D33",
  },
  themeB: {
    name: "Green Blue Neutral",
    primary: "#00A63D",
    secondary: "#2F80ED",
    tertiary: "#A8E6A3",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F3F9F2",
    textLight: "#111111",
    textMutedLight: "#6A6A6A",
    borderLight: "#E2EDE0",
    backgroundDark: "#0D0F0E",
    surfaceDark: "#1A1D1A",
    textDark: "#F5F5F5",
    textMutedDark: "#A8A8A8",
    borderDark: "#282C29",
  },
  // THEME 1 — Blue + Orange + Neutral Gray (Trainerize / Garmin style)
  themeBlueOrange: {
    name: "Blue + Orange",
    primary: "#2F80ED",
    secondary: "#FF8A34",
    tertiary: "#FFB366",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F5F7FA",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    borderLight: "#E1E4E8",
    backgroundDark: "#0C0E12",
    surfaceDark: "#15181D",
    textDark: "#F5F5F5",
    textMutedDark: "#9CA3AF",
    borderDark: "#2A2D33",
  },
  // THEME 2 — Green + Teal (WHOOP / Everfit style)
  themeGreenTeal: {
    name: "Green + Teal",
    primary: "#00A63D",
    secondary: "#2BB7A8",
    tertiary: "#A1EEDB",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F3F9F7",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    borderLight: "#DAEDE9",
    backgroundDark: "#0D0F0F",
    surfaceDark: "#1A1D1D",
    textDark: "#F5F5F5",
    textMutedDark: "#A7A7A7",
    borderDark: "#2A302F",
  },
  // THEME 3 — Red + Black (Apple Fitness+ / Strava style)
  themeRedBlack: {
    name: "Red + Black",
    primary: "#E63946",
    secondary: "#FF5C5C",
    tertiary: "#FF7A7A",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F8F3F3",
    textLight: "#111111",
    textMutedLight: "#666666",
    borderLight: "#E6DADA",
    backgroundDark: "#0B0B0D",
    surfaceDark: "#171719",
    textDark: "#F5F5F5",
    textMutedDark: "#A5A5A5",
    borderDark: "#2E2E30",
  },
  // THEME 4 — Navy + Lime (Peloton / Gymshark style)
  themeNavyLime: {
    name: "Navy + Lime",
    // Brand colors (original palette)
    primary: "#0B1A34",
    secondary: "#A4E12C",
    tertiary: "#C9F77A",
    // Light Mode (original)
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F2F5FA",
    textLight: "#111111",
    textMutedLight: "#666B75",
    borderLight: "#D4D9E3",
    // Dark Mode (original — keep these as they were)
    backgroundDark: "#080A0E",
    surfaceDark: "#11141A",
    textDark: "#F5F5F5",
    textMutedDark: "#9AA0AB",
    borderDark: "#262A32",
  },
  // THEME 5 — Neutral Gray + Accent (Oura / Apple Health style)
  themeNeutralAccent: {
    name: "Neutral + Accent",
    primary: "#4A6CF7",
    secondary: "#E5E7EB",
    tertiary: "#A78BFA",
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F5F5F5",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    borderLight: "#E5E5E5",
    backgroundDark: "#0D0D0D",
    surfaceDark: "#1A1A1A",
    textDark: "#F5F5F5",
    textMutedDark: "#A3A3A3",
    borderDark: "#2D2D2D",
  },
  themeYellowBlueSport: {
    name: "Yellow + Blue",
    primary: "#F7C948",
    secondary: "#1C4F9C",
    tertiary: "#4FA8FF",
    backgroundLight: "#FFFFFF",
    backgroundDark: "#0D1117",
    surfaceLight: "#F5F5F5",
    surfaceDark: "#1A1F25",
    textLight: "#000000",
    textDark: "#FFFFFF",
  },
  orangeGreenAccessible: {
    name: "Orange + Green Accessible",
    // Primary brand colors
    primaryOrange: "#CC6A00", // Accessible bright orange
    primaryGreen: "#00A63D",  // Accessible performance green
    // Supporting colors
    secondary: "#E5E5E5",     // Neutral gray surface
    tertiary: "#2F80ED",      // Blue accent (works with orange & green)
    // Light Mode Tokens
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F7F7F7",
    cardLight: "#FFFFFF",
    borderLight: "#E0E0E0",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    // Dark Mode Tokens (fixed, consistent black UI)
    backgroundDark: "#000000",
    surfaceDark: "#0D0D0D",
    cardDark: "#151515",
    borderDark: "#242424",
    textDark: "#FFFFFF",
    textMutedDark: "#A7A7A7",
  },
  orangeGreenUnified: {
    name: "Orange + Green Unified",
    // Brand Primary Colors (fixed across light/dark)
    primaryOrange: "#FA4F00",  // CTA, highlights
    primaryGreen: "#00A63D",   // Positive metrics, success
    // Supporting neutral & accent colors
    secondary: "#E5E5E5",      // Light surfaces
    tertiary: "#2F80ED",       // Cool accent blue
    // Light Mode Tokens (AA accessible)
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F8F8F8",
    cardLight: "#FFFFFF",
    borderLight: "#DDDDDD",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    // Dark Mode Tokens (AA accessible)
    backgroundDark: "#000000",
    surfaceDark: "#101010",
    cardDark: "#161616",
    borderDark: "#242424",
    textDark: "#FFFFFF",
    textMutedDark: "#A1A1A1",
  },
  orangePower: {
    name: "Orange Power",
    // Main brand colors
    primary: "#FA4F00",         // Bright orange
    primaryHover: "#E34600",    // Accessible hover shade
    // Supporting colors
    secondary: "#F2F2F2",       // Soft neutral gray
    tertiary: "#2F80ED",        // Cool blue accent
    // Light mode tokens
    backgroundLight: "#FFFFFF",
    surfaceLight: "#F8F8F8",
    cardLight: "#FFFFFF",
    borderLight: "#E0E0E0",
    textLight: "#111111",
    textMutedLight: "#6B6B6B",
    // Dark mode tokens
    backgroundDark: "#000000",
    surfaceDark: "#101010",
    cardDark: "#161616",
    borderDark: "#242424",
    textDark: "#FFFFFF",
    textMutedDark: "#A1A1A1",
  },
};

